#!/bin/bash
# narrator-init.sh
# Render the runtime configuration for the narrator container from the
# environment passed in by `podman run --env-file`.
#
# FAIL FAST: a missing required variable stops the boot here, with a message
# naming the variable, rather than letting the app come up half-configured.

set -euo pipefail

log() { echo "[narrator-init] $*"; }
error() { echo "[narrator-init] ERROR: $*" >&2; exit 1; }

# =============================================================================
# Required configuration
# =============================================================================
log "Validating required environment variables..."

if [[ -z "${DOMAIN:-}" ]]; then
    error "DOMAIN is required. Set it to the hostname pointing at this server (e.g. narrator.example.com)"
fi

if [[ -z "${LETSENCRYPT_EMAIL:-}" ]]; then
    error "LETSENCRYPT_EMAIL is required. Set it to an email for Let's Encrypt notifications"
fi

if [[ -z "${SECRET_KEY:-}" ]]; then
    error "SECRET_KEY is required. Generate one with: openssl rand -hex 32"
fi

if [[ -z "${ADMIN_USERNAME:-}" || -z "${ADMIN_PASSWORD:-}" ]]; then
    error "ADMIN_USERNAME and ADMIN_PASSWORD are required - the dashboard is exposed publicly"
fi

if [[ -z "${GROQ_API_KEY:-}" && -z "${GEMINI_API_KEY:-}" ]]; then
    error "At least one LLM key is required: set GROQ_API_KEY or GEMINI_API_KEY"
fi

# =============================================================================
# Optional configuration and defaults
# =============================================================================
# Twitch credentials are optional: without them the dashboard and overlay still
# run, and the UI reports Twitch as disconnected until OAuth is completed.
export TWITCH_CLIENT_ID="${TWITCH_CLIENT_ID:-}"
export TWITCH_CLIENT_SECRET="${TWITCH_CLIENT_SECRET:-}"
export TWITCH_CHANNEL="${TWITCH_CHANNEL:-}"
export TWITCH_REDIRECT_URI="${TWITCH_REDIRECT_URI:-https://${DOMAIN}/auth/callback}"

# Relative to the app service's WorkingDirectory (/var/lib/narrator), so the
# database lands inside the persistent volume.
export DATABASE_URL="${DATABASE_URL:-sqlite:///data/narrator.db}"
export LOG_FORMAT="${LOG_FORMAT:-json}"
export LOG_LEVEL="${LOG_LEVEL:-info}"

if [[ "${LETSENCRYPT_STAGING:-false}" == "true" ]]; then
    log "Using the Let's Encrypt STAGING directory - certificates will not be trusted by browsers"
    export ACME_CA_DIRECTIVE=$'\tacme_ca https://acme-staging-v02.api.letsencrypt.org/directory'
else
    export ACME_CA_DIRECTIVE=""
fi

# =============================================================================
# Log the resolved configuration (never the secrets themselves)
# =============================================================================
log "Configuration:"
log "  DOMAIN: ${DOMAIN}"
log "  LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}"
log "  TWITCH_CHANNEL: ${TWITCH_CHANNEL:-[unset]}"
log "  TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID:+[set]}"
log "  TWITCH_REDIRECT_URI: ${TWITCH_REDIRECT_URI}"
log "  GROQ_API_KEY: ${GROQ_API_KEY:+[set, ${#GROQ_API_KEY} chars]}"
log "  GEMINI_API_KEY: ${GEMINI_API_KEY:+[set, ${#GEMINI_API_KEY} chars]}"
log "  ADMIN_USERNAME: ${ADMIN_USERNAME}"
log "  DATABASE_URL: ${DATABASE_URL}"
log "  LOG_FORMAT: ${LOG_FORMAT}"
log "  LOG_LEVEL: ${LOG_LEVEL}"

# =============================================================================
# Write the application environment file
# =============================================================================
log "Writing /etc/narrator/env..."

mkdir -p /etc/narrator

cat > /etc/narrator/env << EOF
# Generated by narrator-init.sh - regenerated on every container start
TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
TWITCH_CHANNEL=${TWITCH_CHANNEL}
TWITCH_REDIRECT_URI=${TWITCH_REDIRECT_URI}
GROQ_API_KEY=${GROQ_API_KEY:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
SECRET_KEY=${SECRET_KEY}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
DATABASE_URL=${DATABASE_URL}
LOG_FORMAT=${LOG_FORMAT}
LOG_LEVEL=${LOG_LEVEL}
EOF

chmod 600 /etc/narrator/env

# =============================================================================
# Render the Caddyfile
# =============================================================================
log "Rendering /etc/caddy/Caddyfile for ${DOMAIN}..."

if [[ ! -f /etc/caddy/Caddyfile.template ]]; then
    error "Caddyfile.template not found at /etc/caddy/Caddyfile.template"
fi

envsubst '${DOMAIN} ${LETSENCRYPT_EMAIL} ${ACME_CA_DIRECTIVE}' \
    < /etc/caddy/Caddyfile.template \
    > /etc/caddy/Caddyfile

/usr/local/bin/caddy validate --config /etc/caddy/Caddyfile ||
    error "Generated Caddyfile is invalid - check DOMAIN and LETSENCRYPT_EMAIL"

# =============================================================================
# Prepare the persistent state directories
# =============================================================================
log "Preparing state directories..."

# The volume is created empty and root-owned on first run; the app service runs
# as `narrator` and needs to write the SQLite database and Piper voice cache.
mkdir -p /var/lib/narrator/data
chown -R narrator:narrator /var/lib/narrator

mkdir -p /var/lib/caddy

log "Initialization complete"
